# Generated by Django 2.1.5 on 2022-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20220614_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='color',
            field=models.CharField(default='#007bff', max_length=500),
        ),
    ]
