# Generated by Django 2.1.5 on 2022-06-17 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_organisation_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(related_name='event_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='color',
            field=models.CharField(default='#00FF00', max_length=500),
        ),
    ]
