# Generated by Django 2.1.5 on 2022-06-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20220618_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
    ]
