# Generated by Django 2.1.5 on 2022-06-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_remove_event_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.Person')),
            ],
        ),
    ]
