# Generated by Django 2.1.5 on 2022-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_event_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.ImageField(default='C:/Users/User/Pictures/apple.jpg', upload_to='images/'),
        ),
    ]
