# Generated by Django 2.1.5 on 2022-06-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_organisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='C:/Users/User/Pictures/apple.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='C:/Users/User/Pictures/apple.jpg', upload_to='images/'),
        ),
    ]
