# Generated by Django 2.1.5 on 2022-06-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_auto_20220619_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='../static/img/person.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='image',
            field=models.ImageField(default='../static/img/person.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='../static/img/person.jpg', upload_to='images/'),
        ),
    ]
