# Generated by Django 2.1.5 on 2022-06-29 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_auto_20220624_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='update_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
