# Generated by Django 2.1.5 on 2022-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_auto_20220629_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#fc0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='color',
            field=models.CharField(default='#4800ff', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_person',
            field=models.BooleanField(),
        ),
    ]
