# Generated by Django 2.1.5 on 2022-07-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_auto_20220705_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
